// Do not edit this file, it is autogenerated by CMake from the .md file
_HKI( "### Documentation\n"
"\n"
"For the full documentation see [https://docs.anvilcad.com](https://go.anvilcad.com/docs/GetMajorMinorVersion/en/pcbnew/pcbnew.html#custom_design_rules)." );
