/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright (C) 1992-2013 Jean-Pierre Charras <jp.charras at wanadoo.fr>.
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you may find one here:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * or you may search the http://www.gnu.org website for the version 2 license,
 * or you may write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */

/*
 * keyword used in drawing sheet are listed in drawing_sheet.keywords file
 */

/*
 *  Items use coordinates.
 *  A coordinate is defined relative to a page corner
 *  A coordinate is the X pos, the Y pos, and the corner which is the coordinate origin
 *  the default is the bottom right corner
 *  example: (start 10 0 ltcorner) or (start 20 10)
 *  The direction depends on the corner: a positive coordinate define a point
 *  from the corner origin, to the opposite corner.
 *
 *  Items are defined by a name, coordinates in mm and some attributes,
 *  and can be repeated.
 *  for instance (repeat 2) (incrx 2) (incry 2) repeat the item 2 times,
 *  and coordinates are incremented by 2 on X direction, and 2 on Y direction
 *  Comments are allowed. they are inside (), and start by the keyword comment
 *  example:
 *  (comment rect around the title block)
 *
 *  Lines and rect are defined by 2 coordinates start and end, and attributes.
 *  Attributes are linewidth and repeat parameters.
 *  example:
 *  (line (start 50 2 ltcorner) (end 50 0 ltcorner) (repeat 30) (incrx 50) )
 *  (rect (comment rect around the title block) (linewidth 0.15) (start 110 34) (end 2 2) )
 *
 *  Texts are defined by the text (between quotes), the position, and attributes
 *  example
 *  "(tbtext \"1\" (pos 25 1 lbcorner) (font (size 1.3 1.3)) (repeat 100) (incrx 50) )"
 *  the text can be rotated by (rotation <value>) with value = rot angle in degrees
 *  (font (size 1.3 1.3) bold italic) defines a specific size,
 *    with bold and italic options
 *  (justify <justif keyword>) controls the text justification (the default is left)
 *  justif keyword is center, left, right, top and bottom
 *  (justify center top) is a text centered on X axis and top aligned on vertical axis
 *  The text size can be constrained:
 *  (maxlen <value>) and (maxheight <value>) force the actual text x and/or y size to be
 *  reduced to limit the text height to the maxheight value,
 *  and the full text x size to the maxlen value.
 *  If the actual text size is smaller than limits, its size is not modified.
 *
 * Texts can include a format symbol, a la printf.
 * At run time these format symbols will be replaced by their actual value.
 *
 * format symbols are:
 *
 * %% = replaced by %
 * %K = Kicad version
 * %Z = paper format name (A4, USLetter ...)
 * %Y = company name
 * %D = date
 * %R = revision
 * %S = sheet number
 * %N = number of sheets
 * %Cx = comment (x = 0 to 9 to identify the comment)
 * %F = filename
 * %P = sheet path (sheet full name)
 * %T = title
 *
 * example:
 * (tbtext \"Size: %Z\" ...) displays "Size A4" or Size USLetter"
 *
 *  Poly Polygons
 *  Set of filled polygons are supported.
 *
 *  The main purpose is to allow logos, or complex shapes
 *  They support the repeat and rotation options
 *  They are defined by
 *  (polygon (position ..) <rotation>  <linewidth>
 *  the parameter linewidth defines the pen size used to draw/plot
 *  the polygon outlines (default = 0)
 *  example:
 *  (polygon (pos 134 18 rbcorner) (rotate 20)  (linewidth 0.00254)
 *
 *  and a list of corners like
 *  (pts (xy 20.574 8.382) (xy 19.9009 8.382) (xy 19.9009 6.26364) (xy 19.7485 5.98932)
 *  .... )
 *
 *  each sequence like
 *  (pts (xy 20.574 8.382) (xy 19.9009 8.382) (xy 19.9009 6.26364) (xy 19.7485 5.98932)
 *  .... )
 *  defines a polygon.
 *  Each coordinate is relative to the polygon position.
 *  Therefore a "polygon" is in fact a set of polygons, of a poly polygon
 *
 */


// height of the coordinates band 2.0 mm
// coordinates text size 1.3 mm
// default text size 1.5 mm
// default line width 0.15 mm
// frame ref pitch 50 mm

// Default drawing sheet (sizes are in mm)
// Anvil default: Altium-style title block (zone grid kept 50 mm pitch,
// corner-relative so it adapts to any paper size).  Generated by
// make_anvil_sheet.py; the polygon is the traced Anvil mark.
extern const char defaultDrawingSheet[] =
    "(kicad_wks (version 20210606) (generator pl_editor)\n"
    "(setup (textsize 1.5 1.5)(linewidth 0.15)(textlinewidth 0.15)(left_margin 10)(right_margin 10)(top_margin 10)(bottom_margin 10))\n"
    "(rect (name \"\") (start 0 0 ltcorner) (end 0 0) (repeat 2) (incrx 2) (incry 2) (comment \"double border\"))\n"
    "(line (name \"\") (start 50 2 ltcorner) (end 50 0 ltcorner) (repeat 30) (incrx 50))\n"
    "(tbtext \"1\" (name \"\") (pos 25 1 ltcorner) (font  (size 1.3 1.3)) (repeat 100) (incrx 50))\n"
    "(line (name \"\") (start 50 2 lbcorner) (end 50 0 lbcorner) (repeat 30) (incrx 50))\n"
    "(tbtext \"1\" (name \"\") (pos 25 1 lbcorner) (font  (size 1.3 1.3)) (repeat 100) (incrx 50))\n"
    "(line (name \"\") (start 0 50 ltcorner) (end 2 50 ltcorner) (repeat 30) (incry 50))\n"
    "(tbtext \"A\" (name \"\") (pos 1 25 ltcorner) (font  (size 1.3 1.3)) (justify center) (repeat 100) (incry 50))\n"
    "(line (name \"\") (start 0 50 rtcorner) (end 2 50 rtcorner) (repeat 30) (incry 50))\n"
    "(tbtext \"A\" (name \"\") (pos 1 25 rtcorner) (font  (size 1.3 1.3)) (justify center) (repeat 100) (incry 50))\n"
    "(rect (name \"\") (linewidth 0.25) (start 160 33) (end 2 2) (comment \"title block outline\"))\n"
    "(line (name \"\") (start 160 24) (end 2 24))\n"
    "(line (name \"\") (start 160 17) (end 2 17))\n"
    "(line (name \"\") (start 160 10) (end 2 10))\n"
    "(line (name \"\") (start 135 24) (end 135 17))\n"
    "(line (name \"\") (start 55 24) (end 55 17))\n"
    "(line (name \"\") (start 115 17) (end 115 10))\n"
    "(line (name \"\") (start 90 10) (end 90 2))\n"
    "(line (name \"\") (start 55 10) (end 55 2))\n"
    "(polygon (name \"\") (pos 152 28.5) (linewidth 0.02) (pts (xy -4.690 -1.817) (xy -4.690 -1.775) (xy -4.901 -1.563) (xy -5.197 -1.056) (xy -5.197 -0.972) (xy -5.324 -0.676) (xy -5.324 -0.549) (xy -5.366 -0.507) (xy -5.408 0.127) (xy -5.366 0.169) (xy -5.366 0.465) (xy -5.324 0.507) (xy -5.324 0.634) (xy -5.113 1.183) (xy -4.859 1.563) (xy -4.437 1.986) (xy -4.141 2.197) (xy -3.803 2.366) (xy -3.718 2.366) (xy -3.549 2.451) (xy -3.423 2.451) (xy -3.380 2.493) (xy -3.169 2.493) (xy -3.127 2.535) (xy -2.535 2.535) (xy -2.493 2.493) (xy -2.282 2.493) (xy -2.239 2.451) (xy -2.113 2.451) (xy -1.859 2.324) (xy -1.775 2.324) (xy -1.394 2.113) (xy -0.211 1.056) (xy -0.085 1.310) (xy -0.085 1.437) (xy 0.000 1.606) (xy 0.000 1.732) (xy 0.127 2.028) (xy 0.127 2.155) (xy 0.211 2.324) (xy 0.211 2.451) (xy 0.254 2.493) (xy 0.380 2.958) (xy 0.423 2.324) (xy 0.465 2.282) (xy 0.507 1.648) (xy 0.549 1.606) (xy 0.549 1.310) (xy 0.592 1.268) (xy 0.592 0.930) (xy 0.634 0.887) (xy 0.634 0.549) (xy 0.676 0.507) (xy 0.676 0.254) (xy 0.718 0.211) (xy 0.718 -0.169) (xy 0.761 -0.211) (xy 0.761 -0.507) (xy 0.803 -0.549) (xy 0.592 -0.423) (xy 0.296 -0.127) (xy 0.254 -0.127) (xy -1.775 1.648) (xy -2.113 1.817) (xy -2.197 1.817) (xy -2.366 1.901) (xy -2.535 1.901) (xy -2.577 1.944) (xy -3.085 1.944) (xy -3.127 1.901) (xy -3.296 1.901) (xy -3.338 1.859) (xy -3.549 1.817) (xy -4.014 1.563) (xy -4.394 1.183) (xy -4.690 0.676) (xy -4.732 0.423) (xy -4.775 0.380) (xy -4.817 -0.127) (xy -4.775 -0.169) (xy -4.775 -0.423) (xy -4.732 -0.465) (xy -4.690 -0.718) (xy -4.437 -1.183) (xy -4.014 -1.606) (xy -3.761 -1.775) (xy -3.338 -1.944) (xy -3.211 -1.944) (xy -3.169 -1.986) (xy -2.535 -1.986) (xy -2.493 -1.944) (xy -2.197 -1.901) (xy -2.070 -1.817) (xy -1.901 -1.775) (xy -1.648 -1.606) (xy -1.268 -1.268) (xy -0.887 -1.606) (xy -0.887 -1.690) (xy -1.268 -2.070) (xy -1.521 -2.239) (xy -1.859 -2.408) (xy -1.944 -2.408) (xy -2.239 -2.535) (xy -2.451 -2.535) (xy -2.493 -2.577) (xy -3.169 -2.577) (xy -3.211 -2.535) (xy -3.592 -2.493) (xy -4.225 -2.197))(pts (xy -0.423 -3.000) (xy -0.465 -2.408) (xy -0.507 -2.366) (xy -0.507 -2.070) (xy -0.549 -2.028) (xy -0.549 -1.690) (xy -0.592 -1.648) (xy -0.592 -1.352) (xy -0.634 -1.310) (xy -0.634 -1.014) (xy -0.676 -0.972) (xy -0.676 -0.634) (xy -0.718 -0.592) (xy -0.718 -0.296) (xy -0.761 -0.254) (xy -0.761 0.085) (xy -0.803 0.127) (xy -0.803 0.423) (xy -0.845 0.507) (xy -0.549 0.296) (xy -0.254 0.000) (xy 0.085 -0.254) (xy 1.606 -1.606) (xy 1.859 -1.775) (xy 2.282 -1.944) (xy 2.408 -1.944) (xy 2.451 -1.986) (xy 3.127 -1.986) (xy 3.169 -1.944) (xy 3.296 -1.944) (xy 3.338 -1.901) (xy 3.549 -1.859) (xy 3.972 -1.606) (xy 4.394 -1.183) (xy 4.648 -0.718) (xy 4.690 -0.465) (xy 4.732 -0.423) (xy 4.732 -0.127) (xy 4.775 -0.085) (xy 4.775 0.042) (xy 4.732 0.085) (xy 4.732 0.380) (xy 4.690 0.423) (xy 4.690 0.549) (xy 4.606 0.676) (xy 4.606 0.761) (xy 4.352 1.183) (xy 3.845 1.648) (xy 3.507 1.817) (xy 3.423 1.817) (xy 3.254 1.901) (xy 3.085 1.901) (xy 3.042 1.944) (xy 2.535 1.944) (xy 2.493 1.901) (xy 2.324 1.901) (xy 2.282 1.859) (xy 2.070 1.817) (xy 1.732 1.648) (xy 1.268 1.225) (xy 1.183 1.225) (xy 0.845 1.563) (xy 0.845 1.648) (xy 1.352 2.113) (xy 1.944 2.408) (xy 2.197 2.451) (xy 2.239 2.493) (xy 2.451 2.493) (xy 2.493 2.535) (xy 3.085 2.535) (xy 3.127 2.493) (xy 3.507 2.451) (xy 4.014 2.239) (xy 4.394 1.986) (xy 4.817 1.563) (xy 4.944 1.394) (xy 5.197 0.887) (xy 5.197 0.803) (xy 5.282 0.634) (xy 5.366 -0.127) (xy 5.324 -0.169) (xy 5.282 -0.676) (xy 5.239 -0.718) (xy 5.155 -1.056) (xy 4.859 -1.563) (xy 4.606 -1.817) (xy 4.606 -1.859) (xy 4.563 -1.859) (xy 4.183 -2.197) (xy 3.549 -2.493) (xy 3.169 -2.535) (xy 3.127 -2.577) (xy 2.408 -2.577) (xy 2.366 -2.535) (xy 2.028 -2.493) (xy 1.394 -2.197) (xy 0.845 -1.690) (xy 0.803 -1.690) (xy 0.549 -1.437) (xy 0.507 -1.437) (xy 0.169 -1.141) (xy 0.085 -1.225) (xy 0.085 -1.310) (xy 0.042 -1.352) (xy 0.042 -1.479) (xy -0.042 -1.648) (xy -0.042 -1.775) (xy -0.169 -2.070) (xy -0.169 -2.197) (xy -0.254 -2.366) (xy -0.254 -2.493) (xy -0.296 -2.535)))\n"
    "(tbtext \"ANVIL\" (name \"\") (pos 144.5 28.5) (font  (size 3.4 3.4) bold (color 16 163 126 1)) (justify left))\n"
    "(tbtext \"${TITLE}\" (name \"\") (pos 70 28.5) (font  (size 2.6 2.6) bold) (justify center) (maxlen 130))\n"
    "(tbtext \"SIZE\" (name \"\") (pos 159 22.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"${PAPER}\" (name \"\") (pos 147.5 20) (font  (size 1.9 1.9) bold) (justify center))\n"
    "(tbtext \"NUMBER\" (name \"\") (pos 134 22.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"${COMMENT1}\" (name \"\") (pos 95 20) (font  (size 1.9 1.9) bold) (justify center) (maxlen 75))\n"
    "(tbtext \"REVISION\" (name \"\") (pos 54 22.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"${REVISION}\" (name \"\") (pos 28.5 20) (font  (size 1.9 1.9) bold) (justify center) (maxlen 48))\n"
    "(tbtext \"DATE\" (name \"\") (pos 159 15.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"${ISSUE_DATE}\" (name \"\") (pos 137.5 13) (font  (size 1.8 1.8) bold) (justify center))\n"
    "(tbtext \"FILE\" (name \"\") (pos 114 15.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"${FILENAME}\" (name \"\") (pos 58.5 13) (font  (size 1.8 1.8) bold) (justify center) (maxlen 106))\n"
    "(tbtext \"COMPANY\" (name \"\") (pos 159 8.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"${COMPANY}\" (name \"\") (pos 125 5.4) (font  (size 1.9 1.9) bold) (justify center) (maxlen 64))\n"
    "(tbtext \"DRAWN BY\" (name \"\") (pos 89 8.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"${COMMENT2}\" (name \"\") (pos 72.5 5.4) (font  (size 1.6 1.6)) (justify center) (maxlen 32))\n"
    "(tbtext \"SHEET\" (name \"\") (pos 54 8.9) (font  (size 1.1 1.1)))\n"
    "(tbtext \"Sheet ${#} of ${##}\" (name \"\") (pos 28.5 5.8) (font  (size 1.8 1.8) bold) (justify center))\n"
    "(tbtext \"${SHEETPATH}\" (name \"\") (pos 28.5 3.2) (font  (size 1.0 1.0)) (justify center) (maxlen 48))\n"
    ")\n";

extern const char emptyDrawingSheet[] =
    "(kicad_wks (version 20210606) (generator pl_editor)\n"
    "(setup (textsize 1.5 1.5)(linewidth 0.15)(textlinewidth 0.15)\n"
    "(left_margin 10)(right_margin 10)(top_margin 10)(bottom_margin 10))\n"
    "(line (name \"segm1:Line\") (start 0 0) (end 0 0))\n"
    ")\n";
